# ---- sanityprobe : temporary diagnostic-only mod ----
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mod_id=sanityprobe
spec_version=1
mod_version=2.9.0
developer=Yaojihua
archives_base_name=sanityprobe

minecraft_version=1.20
mc_display_version=mc1.20
forge_version=46.0.14

mappings_channel=official
mappings_version=1.20
